// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rklhkerxopgykoosuspm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrbGhrZXJ4b3BneWtvb3N1c3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzUxODMsImV4cCI6MjA2NjM1MTE4M30.ZTrTHdF0p8kFS7JewTJQOeNBuyU_FSytcP9yz51kIUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);